name: Cargo Cache
description: Cache cargo build files and the registry
inputs:
  cache-group:
    description: |
      The group of the cache, defaults to the job ID.
      If you want two jobs to share the same cache, give them the same group name.
    required: false
    default: ${{ github.job }}
  cargo-home:
    description: |
      The location of the Cargo cache files.
      If you specify the `CARGO_HOME` env variable for your commands, you need to set it here too.
      This must NOT end with the trailing slash of the directory.
      Defaults to `~/.cargo`.
    required: false
    default: ~/.cargo
  cargo-target-dir:
    description: |
      Location of where to place all generated artifacts, relative to the current working directory. 
      If you specify the `CARGO_TARGET_DIR` env variable for your commands, you need to set it here too.
      This must NOT end with the trailing slash of the directory.
      Defaults to `target`.
    required: false
    default: target
outputs:
  cache-hit:
    description: |
      A boolean value to indicate if an exact match was found for the key.
      Passed through from the `actions/cache` action.
    value: ${{ steps.cache.outputs.random-number }}
runs:
  using: composite
  steps:
    # The `Cargo.lock` file contains the exact crates used as dependencies.
    # It is important to use for the caching key, because it might become outdated otherwise.
    # If only the `Cargo.toml` file was used, patch releases of crates could cause unnecessary re-compiles.
    # Therefore, if the `Cargo.lock` file does not yet exist (e.g. for libraries), we need to create it first.
    # If the `Cargo.lock` file has been committed to the repo we reuse it to reproduce the same scenario.
    - name: Create Cargo.lock file
      shell: bash
      run: |
        if [ -f "Cargo.lock" ]; then
            echo "Reusing already existing Cargo.lock file."
        else 
            echo "Cargo.lock file does not exist, creating it..."

            # Check if cargo is installed
            cargo --version

            if [ $? -eq 0 ]; then
                # Create Cargo.lock file
                cargo update
                exit $?
            else
                echo "Cargo is not installed!" >&2
                echo "  help: Try using the 'dtolnay/rust-toolchain@master' action before this one." >&2
                exit 1
            fi
        fi

    # The dependencies are recompiled if a new Rust version is used
    # This steps determines the Cargo version to include it in the cache key
    - name: Get cargo version
      id: cargo-version
      shell: bash
      run: |
        # Print version once for debugging
        cargo --version

        # Extract the commit hash and date of the cargo version
        # E.g. "cargo 1.72.0-nightly (0c14026aa 2023-06-14)" becomes "(0c14026aa 2023-06-14)"
        version=$(cargo --version | grep -oE "\(([a-z0-9]+) [0-9-]+\)")

        # Write the extracted version to a GitHub output variable
        # See <https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputs-for-composite-actions>
        echo "cargo-version=$(echo $version)" >> $GITHUB_OUTPUT

    # See <https://github.com/actions/cache>.
    - name: Create cache
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ inputs.cargo-home }}/bin/
          ${{ inputs.cargo-home }}/registry/index/
          ${{ inputs.cargo-home }}/registry/cache/
          ${{ inputs.cargo-home }}/git/db/
          ${{ inputs.cargo-target-dir }}/
        # Update the cache every time the `Cargo.lock` file changes (i.e., the dependencies change).
        # We also include the `Cargo.toml` files in the hash in case the compile configurations change.
        # The Cargo version is also included in the hash, because a version change causes re-compiles
        key: ${{ runner.os }}-${{ steps.cargo-version.outputs.cargo-version }}-${{ inputs.cache-group }}-${{ hashFiles('**/Cargo.toml') }}-${{ hashFiles('**/Cargo.lock') }}
        # Restore caches from the same group.
        restore-keys: |
          ${{ runner.os }}-${{ steps.cargo-version.outputs.cargo-version }}-${{ inputs.cache-group }}-${{ hashFiles('**/Cargo.toml') }}-
          ${{ runner.os }}-${{ steps.cargo-version.outputs.cargo-version }}-${{ inputs.cache-group }}-
